# Generated by Django 3.2.5 on 2021-07-17 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_1', models.CharField(max_length=8)),
                ('ticker_2', models.CharField(max_length=8)),
                ('row_type', models.CharField(choices=[('Stocks_ETFs', 'Stocks or ETFs'), ('Forex', 'Forex')], default='Stocks_ETFs', max_length=12)),
                ('note', models.CharField(max_length=100)),
                ('file_1', models.ImageField(null=True, upload_to='media')),
                ('file_2', models.ImageField(null=True, upload_to='media')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoliopositionsreport.portfolio')),
            ],
        ),
    ]
