# Generated by Django 3.2.5 on 2021-07-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliopositionsreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliorow',
            name='filename_1',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliorow',
            name='filename_2',
            field=models.CharField(default='', max_length=25),
        ),
    ]
