# Generated by Django 3.2.5 on 2021-07-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliopositionsreport', '0002_auto_20210711_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliorow',
            name='filename_1',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='portfoliorow',
            name='filename_2',
            field=models.CharField(default='', max_length=45),
        ),
    ]
