# Generated by Django 3.2.5 on 2021-07-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliopositionsreport', '0003_auto_20210711_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliorow',
            name='filename_1',
        ),
        migrations.RemoveField(
            model_name='portfoliorow',
            name='filename_2',
        ),
        migrations.AddField(
            model_name='portfoliorow',
            name='file_1',
            field=models.ImageField(null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='portfoliorow',
            name='file_2',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
