# Generated by Django 3.2.5 on 2021-07-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliopositionsreport', '0005_auto_20210712_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliorow',
            name='file_1',
            field=models.ImageField(null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='portfoliorow',
            name='file_2',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
