# Generated by Django 3.2.5 on 2021-07-16 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliopositionsreport', '0007_auto_20210713_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='last_update_date',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date and Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time'),
        ),
    ]
